### ISSUE TITLE
parameter 'identity' does not accept $user.identity, expects UserPrincipalName

### ISSUE THREAD

**Issue by dennish78** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#124]
Set-UserBriefingConfig : Cannot validate argument on parameter 'Identity'. The argument "jim.morisson" does not match the
"[a-zA-Z0-9!#$%*+\-/?^_`.{|}~]+@([a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,4}" pattern. Supply an argument that matches
"[a-zA-Z0-9!#$%*+\-/?^_`.{|}~]+@([a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,4}" and try the command again.

**Comment by bergengineering** [comment]
The example CSV in the document shows the correct format '<name>@<company.com>'. It looks like your entry isn't a valid UPN (jim.morrison). If you update your CSV to match, it should work.

**Comment by dennish78** [comment]
I wasn't asking for help. I was pointing out a mistake in either the script or the cmdlet. The example csv has the identity column filled with upn data. Getting a mailbox's identity will not get you the upn. Especially not in a multi domain tenant. The script in the documentation needs to be corrected to use userprinipalname instead of identity, or the cmdlet should work the way the documentation currently claims it does.

**Comment by madehmer** [comment]
@dennish78 - Thanks for asking! Try using "User Principal Name" instead of "User ID Principal Name" for the current user as stored in Azure Active Directory. I'll update the doc accordingly. If that doesn't work, please use [the feedback form](https://cortana.office.com/briefing) to get further assistance for this issue.
