### ISSUE TITLE
No Save option on Opt Out of MyAnalytics page even though instructions page says there is

### ISSUE THREAD

**Issue by luckydad** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#160]
Hi - on this page:
https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/opt-out-of-mya

It says:

"Select Save to save your changes."

I did not see any option to save my changes.

I am pretty sure I was able to opt out of MyAnalytics, but the disconnect between the instructions and the actual interface lowered my confidence that I accomplished opting out of MyAnalytics and reduced my trust in Microsoft in general.

I suggest updating either the instructions or the experience or both so they are consistent.

Thanks for asking for feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a67904-138f-f4f9-af2d-3861b45d606f
* Version Independent ID: 9b55a580-c1fb-d28c-d415-361ea74f53e7
* Content: [Opt out of MyAnalytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/opt-out-of-mya)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/opt-out-of-mya.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/opt-out-of-mya.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-pausch**

**Comment by paul9955** [comment]
Hi luckydad,

Thank you so much for calling this to my attention! You're absolutely right. When I initially wrote and posted this page, we had a **Save** button but it's since been removed. 
I've fixed the page and you can see it here: [Opt out of MyAnalytics](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/opt-out-of-mya).

Thanks again!
 - Paul 
(MyAnalytics documentation)
