### ISSUE TITLE
Allow MANUAL selection of Focus time

### ISSUE THREAD

**Issue by mgerity** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#198]
The idea of scheduling Focus time a couple of weeks out is great, but leaving it to a machine to try and pick the times is a terrible waste of this concept.

Why not simply let us pick times ourselves?  There are items that are on my calendar so that I am aware of them (for example, somewhere my wife or kids need to be), but that I can schedule Focus time over.  There are items that are on my calendar (like time blocking that I do myself) that are completely consistent with Focus time.  The system cannot figure these kinds of issues out, but I can, easily.  This instantly renders the whole system worthless, because we're stuck with the automated system.  I could get Focus times scheduled despite these kinds of issues in a matter of seconds, but no, it's 100% automated or nothing.  Why? 

Further, if I were to notice during scheduling of Focus time that my calendar didn't have enough time blocks available, I could engage in some rearranging of my calendar to clear some spaces for Focus time.  There is no opportunity for this when the system has already analyzed my calendar and picked times.  To make matters worse, the system appears to do no reanalysis whatsoever after changes are made.  I auto-applied Focus times, and then realized it picked slots earlier in the day than I wanted. 
 So, I changed the settings to make the earliest start time later, but it left the early blocks in place.  I then left the plan and then ran it again, and there they were, still in the time slots that didn't conform with my changed preference settings.  Clearly it is failing to reanalyze and adjust, which is a problem we just wouldn't have if we could manually set our Focus time blocks.

Has it dawned on nobody that users might like to pick their own times manually?

**Comment by paul9955** [comment]
Hi mgerity,
Thanks for your interest in focus time. I'm going to pass your comments on to the product team, but first I have a couple of questions:
  #1. In your example about items in your calendar that are reminders (where you said, "somewhere my wife or kids need to be"), are you saying that you'd want that day's focus time to _coincide_ with some or all of the reminder -- so that the reminder block and the focus-time block overlap (partly or completely)?  
  #2. Related to #1, have you tried dragging and dropping a focus-time block after it has been created? (I myself do this occasionally, either in anticipation of a meeting that I know will be scheduled or to just move the block to a time of day when I know it will benefit me more.) You can reschedule focus time this way either to an empty stretch in your calendar or to scheduled time, in which case both blocks would occur simultaneously.   
Thank you! 
 -- paul9955

**Comment by mgerity** [comment]
Thank you for your response.

Yes, on question #1, I'm saying that I have things on my calendar that really are not commitments for ME, and therefore I can have focus time sessions scheduled on top of those things.  Of course, the AI that plugs the focus time sessions into my calendar doesn't know that these are not my commitments, so it avoids those time blocks.

As for question #2, I did find out after I posted that I can move the automatically scheduled times around, and some people have even come up with Power Automate routines that use a copied focus time block.  That's helpful, but I'd still just prefer to pick my own times from the get go.

**Comment by paul9955** [comment]
Hi mgerity,
Here's a note about the situation in Q1. You might already know this, but take a look at [Add time away from the Office to Co-workers' Outlook Calendars](https://support.microsoft.com/en-us/office/add-time-away-from-the-office-to-coworkers-outlook-calendars-69fe38aa-7b5f-4225-8b69-47f47092e65e?ui=en-us&rs=en-us&ad=us). Step 5 includes a reminder to set **Show As** to "Free" when you add your own away time to someone else's calendar. If that step is followed, your time will not show as "Busy" or "Do not Disturb" either for other people who want to invite you to a meeting, or to the Focus-time scheduler. (I currently have such a time block on my calendar. My manager sent it and then my focus time was scheduled on top of it without any conflict.) 
 -- paul9955
 P.S. I believe that this even works if you change the **Show As** setting of a block of time to "Free" manually. I'm testing this out right now. I just created a six-hour appointment for myself on Tuesday, March 9th and set it to "Free" time. As soon as the week of March 8-14 comes into range for Focus-time scheduling, I'll know whether it places my two-hour block for that day at 8:00 AM (as I suspect it will) or at 2:00 PM (after this test appointment is over). I'll let you know what I discover.

**Comment by paul9955** [comment]
Hello mgerity,
I have the results of my test. I had scheduled a six-hour appointment for 8 AM - 2 PM on March 9th with **Show As** set to "Free." The focus-time feature blocked out time for me on that day from 8 AM to 10 PM. So, the feature _does_ take the **Show As** value into account. I believe this addresses the first of your concerns.

**Comment by paul9955** [comment]
Hi mgerity,
I've passed your comments on to the product team so that they can take your ideas into consideration for future updates. In the meantime, I'm going to close the issue, but if you have further questions about the current functioning of the feature, feel free to re-open it and ask. 
thank you,
 -- paul9955

**Comment by SJacksonWHA** [comment]
This is a closed item, but thought I'd drop one more suggestion - Have the Show As or Category be "Focus Time", so it will automatically see and acknowledge there is Focus Time already scheduled.  I too manually put in focus times based on set meetings.  It is never the same time each day.   I came to this forum specifically to ask if this could be an option.
