### ISSUE TITLE
Cortana should be configurable to everyone's work schedule

### ISSUE THREAD

**Issue by MMMan2010** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#203]
I work in the middle east where the work week is Sun-Thu, however Cortana only arrives on Monday's through Friday's.  The same would be true of anyone who's on shift work, 10 on/10 off and various other methods of working, aside from the solo Mon-Fri work week that Cortana seems to support.  This product shouldn't be so stringent in it's application as it's a useful tool when it works, but not very useful if you can't get the information you need, when you need it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a83186-6909-edb8-7de3-7a5c9307a0a1
* Version Independent ID: 9ba1d4d8-60ba-1c4d-f7e8-e9a92e74727d
* Content: [Briefing email overview - Cortana](https://docs.microsoft.com/en-us/briefing/be-overview#feedback)
* Content Source: [Briefing/be-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Briefing/be-overview.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@MMMan2010 - Thanks for your feedback. You can change [Settings for Briefings](https://docs.microsoft.com/briefing/be-settings) here: [https://cortana.office.com/briefing](https://cortana.office.com/briefing).

**Comment by MMMan2020** [comment]
You completely missed the point of what this issue is.  You can't just close a logged issue because you "say a few words" or "think you're right".  You clearly haven't actually tested this functionality, or you'd KNOW it doesn't work the way you said.  

I've had the timezone set to my world zone the entire time (it was done so by my organization - currently UTC +4, Abu Dhabi).  That doesn't equate to a Sunday-Thursday work week within Cortana.  I still ONLY get messages about Cortana briefings from Monday to Friday, **completely contrary to the exact issue I logged**.  

Next time, try your solution first to see if it's accurate.  Give it some time, and talk to some people on the product team.  This is NOT a closed issue.
