### ISSUE TITLE
Unable to leave a Focus Plan

### ISSUE THREAD

**Issue by smacsween** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#207]
You can delete the scheduled Focus Plan but this does not update Outlook.

**Comment by paul9955** [comment]
Hi smacsween,
Yes, if you leave a focus plan, any already scheduled focus-plan blocks on your calendar remain on your calendar. Of course, you can delete them by hand, but I know of no way to delete them all at once. At any time, there should be no more than ten focus plan blocks spread out over the next two weeks of your schedule. 
I communicated your observation to the product team, and I’ve already heard back from them. As it turns out, they actually have a plan to delete focus blocks from the calendar for a person who has left the focus plan, but I do not have an ETA for this feature enhancement. 
Thank you for your interest and for reaching out with your comment!
 -- paul9955
