### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#224]
The links to Management and coaching and External collaboration under Take Action on this page are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c33146-d9d5-d9d4-21b3-b78fd3aff064
* Version Independent ID: 9335bcff-af09-db03-79fd-6eaed8460b59
* Content: [Increase customer focus with Workplace Analytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/use/customer-focus)
* Content Source: [WorkplaceAnalytics/Use/customer-focus.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Use/customer-focus.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@juchacz - These need the language added to the URL within the App. GitHub will error if I add it to the link because the user must enter their preferred language code. For example for English, you'd add **en-us/** to the following External Collaboration URL within the WpA App: https://workplaceanalytics.office.com/en-us/Home/Agility/ExternalCollaboration - So I'll something that explains this to the docs, so people don't think they're broken links.

**Comment by madehmer** [comment]
@juchacz - For now, I simply added en-us/ to all the Workplace Analytics app links with the assumption that people using the app in other languages will figure it out. It's not the best solution but it'll work for now.
