### ISSUE TITLE
Rename focus time

### ISSUE THREAD

**Issue by ContentbyDave** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#229]
Can i rename the focus time in my calendar,  Also can i have multiple streams of focus time? for example 1 hour a day to "study for exam" and one hour a day to "prepare for conference".  I love the dynamic scheduling.  Can i apply it to a recurring meeting with 2  or more people?

**Comment by paul9955** [comment]
Hi ContentbyDave,
As for renaming, you can rename individual focus-time blocks by hand (in your calendar, double-click the block and then edit the **Title** field), but I suspect that you were looking for a way to rename them in bulk, correct? 
As for having multiple streams, that's a good idea. I'll contact the product team to see if they know of a way to do that. 
I'll also ask about the dynamic scheduling for meetings with others. 
 -- paul9955

**Comment by rgroh11** [comment]
Along this same line of being able to customize the focus time, is there a way to select the category (from the customized categories we each already have in Outlook) so that anytime MyAnalytics adds Focus Time to my calendar, it is already classified as the category I want?

**Comment by paul9955** [comment]
Hi ContentbyDave,

I contacted the product team and gave them your suggestions. They responded with these answers:

Q1. Can you have separate “streams” of focus time, each one dedicated to a particular recurring task? (If not, is there a workaround other than just renaming multiple individual focus-time blocks by hand?)
A1. For now, we do not have that functionality. We are definitely exploring how we can provide more meaningful experiences for focus time. Renaming the focus blocks is the best workaround so far.

Q2. Outlook offers the ability to customize categories. Can I assign these categories to my focus-time blocks?
A2. At the moment, you cannot. However, we are working to give users the ability to assign categories to calendar appointments. The work is currently ongoing but we do not have an ETA for it.  

Q3. Can I let a recurring meeting (with other people) be scheduled dynamically, using an algorithm similar to the one used to schedule focus time, rather than by hand? 
A3. No, we do not have this feature available. We've taken this feedback and we'll explore the possibility.

Thank you for these ideas! As soon as any of them come to fruition, I'll update the [product documentation](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/mya-elements) accordingly. I'm going to close this issue for now. If you have further comments or questions, feel free to re-open it. 

-- paul9955
