### ISSUE TITLE
Instant message response time

### ISSUE THREAD

**Issue by rafniedz** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#237]
For support employees it's important to keep KPI's like instant message response time. Can I track somehow my response times for my peers? How can I collect such a statistics per particular person or group in some period of time (a week, a month or so + historical data for comparison) ?

**Comment by paul9955** [comment]
Hello rafniedz,
This capability is not available in the product right now, but I have conveyed your question/suggestion about KPIs (and in particular, response times) to the product team so that they can consider it for future releases. 
Thank you for your interest in our IM feature and for your suggestion,
 -- paul9955
