### ISSUE TITLE
Focus time booked by MyAnalytics includes notification

### ISSUE THREAD

**Issue by sanysaab** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#251]
Hello,

I'm not 100% sure if this is an intended feature or an issue. I see this as an issue so i'm submitting it here :

Focus time booked by MyAnalytics in Outlook seems to be using the default calendar setting (in my case, notifies me 15 min before meeting start). As a result, i'm notified for every focus time scheduled. I'm trying to reduce notification pollution and I feel this is opposite to the goal of the tool (MyAnalytics focus helps you focus). 

The default behaviour should be (in my opinion) that MyAnalytics forces a RemindMe = never.

Thank you,
Sany Saab

**Comment by paul9955** [comment]
Hi sanysaab,

I contacted the product team about this and I passed on your concern. They responded and told me that this is a known issue. Other MyAnalytics users had commented on it previously, it turns out, and the issue is being worked on at this time, although they couldn't give me an ETA for the appearance of a solution.   

Thank you for your interest in this feature, 
 -- paul9955
