### ISSUE TITLE
Requirements correct for GCC customers?

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#254]
This report is not showing up for O365 GCC customers. Is this expected and the documentation is inaccurate about the requirements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5ef7706-e7ef-d00b-6482-269bd9ff6fb2
* Version Independent ID: 8f4d51a6-c0fd-1899-c4df-3e6da402b19a
* Content: [Business continuity report - Workplace Intelligence](https://docs.microsoft.com/en-us/Workplace-Analytics/tutorials/bcrps)
* Content Source: [WorkplaceAnalytics/Tutorials/bcrps.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Tutorials/bcrps.md)
* Product: **wpa**
* GitHub Login: @madehmer
* Microsoft Alias: **v-mideh**

**Comment by madehmer** [comment]
@npherson - Thanks for asking. Only company's who have at least 100 active MyAnalytics users can see the [Business continuity report](https://docs.microsoft.com/Workplace-Analytics/tutorials/bcrps#q4-who-is-eligible-to-see-this-report) report and since [MyAnalytics does not support GCC environments](https://docs.microsoft.com/Workplace-Analytics/myanalytics/overview/plans-environments#environment-support), they unfortunately cannot see this report.

**Comment by npherson** [comment]
MyAnalytics has been in GCC for several years now.

**Comment by madehmer** [comment]
@npherson - Apologies for misreading it. If you have confirmed at least 100 MyAnalytics users are opted in, then this issue might be a bug. Would you please select **Feedback** in the left navigation of your [MyAnalytics dashboard](https://myanalytics.microsoft.com/), explain your issue, select the checkbox to allow Microsoft to contact you about it, and then submit it? That way the team can follow up directly with you. Thanks!
