### ISSUE TITLE
Automate Org Data Upload

### ISSUE THREAD

**Issue by toddjohnson39** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#44]
Is there a way to automate the process of upload/map/validate for org data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0746231-3c38-d024-7a2c-48bb48bed59b
* Version Independent ID: b2e61773-3f27-079f-647c-8d7e01f9e97b
* Content: [Upload organizational data to Workplace Analytics (subsequent uploads) - Workplace Analytics Office 365 ](https://docs.microsoft.com/en-us/workplace-analytics/setup/upload-organizational-data)
* Content Source: [WorkplaceAnalytics/Setup/Upload-organizational-data.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/Setup/Upload-organizational-data.md)
* Product: **wpa**
* GitHub Login: @paul9955
* Microsoft Alias: **v-midehm**

**Comment by paul9955** [comment]
Hello Todd,
Unfortunately, there is no way to automate this task other than to use the Workplace Analytics portal itself. You could conceivably write a script to validate your .csv file (check for correct format, non-null values, and so on) before you upload the file. But we don't recommend this because this kind of validation would essentially duplicate what Workplace Analytics does anyway, after upload. 
Thank you,  - Workplace Analytics doc team
