### ISSUE TITLE
Add-ons Unavailable from Home Screen

### ISSUE THREAD

**Issue by tim-white-esri** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#57]
Using Outlook for Mac, the Insights add on (along with others such as Evernote, Workfront, and OneNote) are grayed out on the home screen. They are only enabled inside of an email. 

While understandable to an extent for Send to Evernote, etc; Insights should be available from the home screen.

**Comment by paul9955** [comment]
Hello Tim,
I am passing this on to the PM & development team. First, I'll ask them to look into it as an improvement and next, I'll try to find out whether there's a workaround. If there is, I'll reply back in this space. 
Thank you,
  -- paul9955

**Comment by paul9955** [comment]
Hi Tim,
I contacted the product team about this. They responded that "this is the current behavior of add-ins. We are working to improve the discoverability of Insights and make them available in other contexts, too, not just when an email is selected." 
Unfortunately, I can't give an ETA for these improvements because they are still in development. 
Thank again Tim, 
 -- paul9955

**Comment by tim-white-esri** [comment]
Thank you for the follow up @paul9955. Hopefully it won't be too long.
