### ISSUE TITLE
Lunchtime

### ISSUE THREAD

**Issue by quietthings** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#99]
"MyAnalytics considers the time from 12:00 AM to 1:00 PM as time for the midday meal" should be 12:00 PM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f032f9-30a5-b801-b3c2-602a6ef552d3
* Version Independent ID: bffa68c6-76a6-3de4-ec42-ab75c6a264d2
* Content: [Focus plan - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/focus-plan#feedback)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/focus-plan.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **paul9955**

**Comment by madehmer** [comment]
@quietthings -Thank you for your feedback! Please check your [Outlook settings](https://outlook.office.com/calendar/options/calendar/view/appearance) to confirm your working hours are set up. If that doesn't fix it, this might be a bug. If you think it's a bug, would you please go to [your dashboard](https://myanalytics.microsoft.com/), select **Feedback** near the bottom of the left navigation pane, and then fill out and submit your issue there? Please select the **Allow Microsoft to contact you** checkbox. Then the team can follow up and confirm if it's a bug and/or how they can help you get your focus scheduling prompts back!
![feedback](https://user-images.githubusercontent.com/39922363/76039566-a40ad200-5f01-11ea-9173-0bebbf7976cd.png)

**Comment by kirashi3** [comment]
@madehmer apologies, but I think you may have misunderstood the ask here.

@quietthings wants the documentation to be updated. Right now it seems to indicate that lunch time should be 12 hours long, since that's the amount of time between 12:00 AM midnight and 1:00PM just after the "noon" hour... If this needs changing, can this be addressed?

#### Current
> MyAnalytics considers the time from 12:00 AM to 1:00 PM as time for the midday meal. 

#### Proposed
> MyAnalytics considers the time from 12:00 PM to 1:00 PM as time for the midday meal. 

https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/focus-plan#lunchtime
![image](https://user-images.githubusercontent.com/5917227/77200300-83b54880-6aa7-11ea-95e0-375282101a4d.png)

**Comment by Absoblogginlutely** [comment]
@madehmer - this issue is still incorrectly documented in this page and needs to be updated to "12:00pm to 1:00 PM"
